### ISSUE TITLE
Pausing Video on Close and Side Click

### ISSUE THREAD

**Issue by brandleesee** [darkylmnx/jQuery-Youtube-Url-To-FullScreen-Video-Lightbox#3]
The issue I am having is summarized in the following video:
Link fixed! [https://youtu.be/HPeLiaPdhF8](https://youtu.be/HPeLiaPdhF8)

The plugin works perfectly, however, visitors to the website might be dumbfounded if on clicking X (close) or side clicking, the video they were watching keeps on playing.

Thus, may I ask if there is a way to pause the video when X is clicked or a side click is performed?

I am not conversant with jquery/javascript and as such am unable to contribute to the actual code developing. I can only point out my difficulty. If this is already implemented, please point me towards the settings/options I have to alter.

Thanks in advance,
Brandon

**Comment by darkylmnx** [comment]
hi, thanks a lot for the feedback,i think you have an old version of the plugin. We added a stop video on close in our latest version :)

you can just download the new js file and it will be okay

**Comment by brandleesee** [comment]
Unfortunately, the lightbox is gone and on clicking the thumbnail to play the video, I am sent to the video's YouTube page. I used the downloads from the src/ folder.

Is there a solution for this?
Should I use the 'old' script and css and maybe be given the 'added' code to stop on close?

Thanks once again,
Brandon

**Comment by darkylmnx** [comment]
on which browser did you try ? could you send me a link to your demo please because i tried before replying to you and everything works with the file in the src. You can show me a demo on a jsfiddle ou plunkr if you didn't host it.

**Comment by brandleesee** [comment]
Google Chrome, Firefox and Opera.
All is ok.
I had the impression that it was not functioning due to browser caching/dropbox hosting etc and it seemed to be true. 
Used here:
[https://dl.dropboxusercontent.com/u/47163633/VaniWeb/html5up-astral/index.html#videography](https://dl.dropboxusercontent.com/u/47163633/VaniWeb/html5up-astral/index.html#videography)
Website is still a work in progress.
Cheers for your help.

**Comment by darkylmnx** [comment]
No prob
