### ISSUE TITLE
doesn't seem to read the delay start 

### ISSUE THREAD

**Issue by lucasverra** [darkylmnx/jQuery-Youtube-Url-To-FullScreen-Video-Lightbox#5]
lV36s?**t=15s**

Thanks for your work 👍

**Comment by darkylmnx** [comment]
@lucasverra I'll check this out ASAP and get back to you

**Comment by darkylmnx** [comment]
@lucasverra check the new release

**Comment by lucasverra** [comment]
Works like a charm from a charming place . Thanks for the quick fix.
I owe you a 🍺when in Paris

**Comment by darkylmnx** [comment]
With pleasure !
